// backend/services/geminiService.js
// Direct Google Gemini REST API Client with multi-model fallback, conversation memory, and low-latency settings

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models';

// High-speed, highly available free-tier models in priority order
const MODEL_FALLBACK_LIST = [
  'gemini-flash-lite-latest',
  'gemini-3.1-flash-lite',
  'gemini-3.5-flash-lite',
  'gemini-3.6-flash',
  'gemini-3.7-flash'
];

/**
 * Robust helper to call Gemini generateContent with auto-fallback across available models
 */
async function callGemini({
  prompt,
  systemInstruction = '',
  responseJson = false,
  temperature = 0.4,
  maxOutputTokens = 2200,
  timeoutMs = 25000
}) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is missing in environment variables');
  }

  let lastError = null;

  for (const model of MODEL_FALLBACK_LIST) {
    const url = `${GEMINI_API_BASE}/${model}:generateContent?key=${apiKey}`;

    const requestBody = {
      contents: [
        {
          role: 'user',
          parts: [{ text: prompt }]
        }
      ],
      generationConfig: {
        temperature,
        maxOutputTokens
      }
    };

    if (systemInstruction) {
      requestBody.systemInstruction = {
        parts: [{ text: systemInstruction }]
      };
    }

    if (responseJson) {
      requestBody.generationConfig.responseMimeType = 'application/json';
    }

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
        signal: controller.signal
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorText = await response.text();
        console.warn(`[Gemini API] Model ${model} returned status ${response.status}. Trying fallback model...`);
        lastError = new Error(`Gemini [${model}] status ${response.status}: ${errorText}`);
        continue;
      }

      const data = await response.json();
      const candidate = data.candidates?.[0];
      const text = candidate?.content?.parts?.[0]?.text;

      if (!text) {
        lastError = new Error(`No text generated by model ${model}`);
        continue;
      }

      return text.trim();
    } catch (err) {
      clearTimeout(timeoutId);
      console.warn(`[Gemini API] Error with ${model}:`, err.message);
      lastError = err;
    }
  }

  throw lastError || new Error('All Gemini fallback models failed to respond.');
}

/**
 * Generate interview response / dynamic question with conversation memory
 * Comprehensive Technical Interviewer covering:
 * - DSA & Problem Solving (Dynamic rotation across Patterns: Trees, Graphs, DP, Stacks, Binary Search, Sliding Window, Heaps)
 * - CS Core Subjects: Operating Systems, DBMS & SQL, Computer Networks, OOP & System Architecture
 * - Live Code Analysis (C/C++, Python, Java, SQL)
 * - Resume Background & Experience
 */
async function getInterviewBotResponse(userMessage, systemContext, isFirstMessage = false, messageCount = 1, history = []) {
  try {
    const formattedHistory = history.length > 0
      ? history.map(h => `${h.sender === 'candidate' ? 'Candidate' : 'Interviewer'}: ${h.text}`).join('\n\n')
      : 'None (Opening Turn)';

    const systemPrompt = `You are an elite Senior Principal Technical Bar-Raiser at top tech companies (Google, Meta, Microsoft, Amazon).
You conduct highly rigorous, realistic technical interviews that balance:

1. DIVERSE DSA & PROBLEM SOLVING (Broad Pattern Rotation):
   - Binary Trees & BSTs (e.g. Lowest Common Ancestor, Tree Path Sum, Validate BST, Level Order)
   - Graphs, BFS/DFS & Topo Sort (e.g. Number of Islands, Course Schedule, Clone Graph, Word Ladder)
   - Dynamic Programming & Memoization (e.g. Coin Change, Longest Increasing Subsequence, House Robber, Word Break)
   - Sliding Window & Two Pointers (e.g. Container With Most Water, Minimum Window Substring, 3Sum, Longest Substring Without Repeating Characters)
   - Binary Search & Rotated Arrays (e.g. Search in Rotated Sorted Array, Find Peak Element, Koko Eating Bananas)
   - Stack & Monotonic Stack (e.g. Daily Temperatures, Largest Rectangle in Histogram, Valid Parentheses, Min Stack)
   - Priority Queues & Heaps (e.g. Kth Largest Element, Merge K Sorted Lists, Task Scheduler)
   - SQL & Relational Queries (e.g. Window Functions, Nth Highest Salary, Self Joins, Subqueries)

2. COMPUTER SCIENCE CORE FUNDAMENTALS:
   - Operating Systems: Process vs Thread, Virtual Memory & Paging, Deadlocks & Semaphores, Context Switching, CPU Scheduling.
   - DBMS: B-Trees vs LSM Trees vs Hash Indexes, ACID properties, Transaction Isolation levels, Sharding, Replication & Normalization.
   - Computer Networks: TCP 3-Way Handshake vs UDP, HTTPS/TLS Handshake, WebSockets, DNS Resolution flow, Load Balancing (L4 vs L7).
   - System Design & Architecture: Caching strategies (Redis/Memcached, Cache-Aside vs Write-Through), Concurrency, Microservices tradeoffs.

3. CANDIDATE RESUME CONTEXT:
${systemContext}

INTERVIEW PROGRESSION & NO-REPEAT RULES:
- CRITICAL: NEVER repeat or re-ask a problem, question, or topic already asked in the conversation history below. Each question MUST test a fresh concept or distinct algorithm pattern.
- Turn 1: Greet the candidate and ask a focused system architecture question from their resume background.
- Turn 2-3: Transition into a deep Computer Science Core question (OS, DBMS, or Networks) relevant to software engineering.
- Turn 4+: Challenge them with a distinct DSA problem or SQL scenario, inviting them to write and submit their solution in the Live Code Editor.
- When evaluating candidate code submissions ([CODE_SUBMISSION:...]):
  * Rigorously evaluate algorithmic correctness and edge cases.
  * State the exact Time and Space Complexity (e.g. O(N) time, O(1) auxiliary space).
  * Give 2-3 sentences of constructive feedback and either present an optimization challenge or rotate to the next technical topic.
- Format: Keep total response to 2-4 complete sentences max so the interview stays interactive and fast-paced. Always end with a direct question.`;

    let prompt = "";
    if (isFirstMessage) {
      prompt = `Start the technical mock interview session. Welcome the candidate, state the scope (System Experience, CS Core Fundamentals, and Algorithmic Problem Solving), and ask your first focused question based on their resume background.`;
    } else if (userMessage.includes("[CODE_SUBMISSION")) {
      prompt = `SESSION HISTORY:
${formattedHistory}

The candidate has submitted code through the Live Code Editor:
---
${userMessage}
---
Analyze their code carefully for correctness, edge cases, and Big-O Time & Space complexity. Provide constructive feedback and ask the next technical follow-up.`;
    } else {
      prompt = `SESSION HISTORY SO FAR:
${formattedHistory}

LATEST CANDIDATE RESPONSE:
"${userMessage}"

Interview Turn #${messageCount}. Evaluate their response. Transition to the next technical topic (rotate between CS Core Fundamentals: OS/DBMS/Networks, or pick a FRESH DSA coding pattern that has NOT been asked yet in this session). Keep your response concise (2-4 sentences), complete, and end with a clear direct question.`;
    }

    const reply = await callGemini({
      prompt,
      systemInstruction: systemPrompt,
      temperature: 0.7,
      maxOutputTokens: 800,
      timeoutMs: 18000
    });

    return reply;
  } catch (err) {
    console.warn('[Gemini Interview Bot Fallback]:', err.message);
    if (isFirstMessage) {
      return "Welcome to your technical mock interview. We'll be covering system engineering from your resume, Computer Science fundamentals (OS, DBMS, Networks), and DSA problem solving. To begin, could you walk me through the architecture and key tradeoffs of your most challenging project?";
    } else if (userMessage.includes("[CODE_SUBMISSION")) {
      return "I've reviewed your submitted solution. The logic is clean and handles the primary cases well. What is the worst-case Time and Space complexity of your approach, and how would you optimize it if memory was constrained to O(1) auxiliary space?";
    } else {
      const fallbackQuestions = [
        "That's a solid explanation. Let's look at binary tree algorithms: How would you determine the Lowest Common Ancestor (LCA) of two given nodes in a Binary Search Tree versus a generic Binary Tree?",
        "Good points. In distributed systems, how does database indexing using B+ Trees compare to Hash-based indexes for range queries versus point lookups?",
        "Well answered. Let's shift to graph traversal: How would you detect a cycle in a directed graph using Kahn's algorithm or Topological Sort?",
        "Clear explanation. In Operating Systems, how does the OS handle page faults in virtual memory, and what are the tradeoffs of the LRU page replacement algorithm?",
        "Understood. Moving to dynamic programming: How would you formulate the recurrence relation to solve the Coin Change problem (minimum coins to make amount X) in O(amount * n) time?"
      ];
      const randomFallback = fallbackQuestions[Math.floor(Math.random() * fallbackQuestions.length)];
      return randomFallback;
    }
  }
}

/**
 * Generate comprehensive rubric evaluation and feedback after interview finishes
 */
async function generateInterviewFeedback(transcript, role = "Software Engineer") {
  try {
    const formattedTranscript = transcript
      .map(t => `${t.sender === 'bot' ? 'Interviewer' : 'Candidate'}: ${t.text}`)
      .join('\n\n');

    const prompt = `You are a Principal Bar-Raiser at a Tier-1 tech company evaluating a completed technical interview for a "${role}" position.

FULL INTERVIEW TRANSCRIPT:
----------------------------------------
${formattedTranscript}
----------------------------------------

Evaluate the candidate's performance across 4 dimensions:
1. Technical Depth & Domain Expertise (Resume & Frameworks)
2. Computer Science Core Fundamentals (OS, DBMS, Networks, Architecture)
3. Algorithmic Problem Solving & Code Quality (Correctness, Complexity, Edge cases)
4. Communication Clarity & Engineering Tradeoffs

Output ONLY a valid JSON object matching this schema:
{
  "score": <overall integer score from 0 to 100>,
  "feedback": "<Detailed 3-5 sentence breakdown highlighting key technical strengths, areas for improvement, and algorithmic precision observed in this session>",
  "strengths": ["<strength 1>", "<strength 2>", "<strength 3>"],
  "improvements": ["<improvement 1>", "<improvement 2>", "<improvement 3>"],
  "rubricBreakdown": {
    "technicalAccuracy": <integer 0-100>,
    "problemSolving": <integer 0-100>,
    "communication": <integer 0-100>,
    "codeEfficiency": <integer 0-100>
  }
}`;

    const responseText = await callGemini({
      prompt,
      responseJson: true,
      temperature: 0.3,
      maxOutputTokens: 1200
    });

    const parsed = JSON.parse(responseText);
    return {
      score: parsed.score || 75,
      feedback: parsed.feedback || "The candidate demonstrated solid technical knowledge and problem-solving capability throughout the interview.",
      strengths: parsed.strengths || ["Clean problem-solving", "Good communication"],
      improvements: parsed.improvements || ["Handle more edge cases", "Elaborate deeper on memory tradeoffs"],
      rubricBreakdown: parsed.rubricBreakdown || {
        technicalAccuracy: parsed.score || 75,
        problemSolving: parsed.score || 75,
        communication: 80,
        codeEfficiency: parsed.score || 70
      }
    };
  } catch (err) {
    console.error('Feedback generation error:', err);
    return {
      score: 72,
      feedback: "The candidate communicated clearly and demonstrated solid technical understanding across the interview topics.",
      strengths: ["Clear communication", "Structured approach"],
      improvements: ["Provide deeper algorithmic complexity analysis", "Consider additional edge cases"]
    };
  }
}

/**
 * Perform predictive ATS Diagnostics on a resume PDF against a target role
 */
async function generateATSIntel(resumeText, targetRole) {
  try {
    const prompt = `You are a Senior Technical Recruiter & ATS Analytics Engine.
Analyze the following candidate resume text against the target role: "${targetRole}".

RESUME TEXT:
----------------------------------------
${resumeText}
----------------------------------------

Evaluate ATS keyword match, missing tools, metric quantification, and structural clarity.

Output ONLY a valid JSON object matching this schema:
{
  "score": <integer from 0 to 100 representing ATS match rate>,
  "keywords": ["<missing keyword 1>", "<missing keyword 2>", "<missing keyword 3>", "<missing keyword 4>", "<missing keyword 5>"],
  "improvements": [
    "<Actionable improvement 1 with specific advice>",
    "<Actionable improvement 2 with specific advice>",
    "<Actionable improvement 3 with specific advice>"
  ]
}`;

    const responseText = await callGemini({
      prompt,
      responseJson: true,
      temperature: 0.2,
      maxOutputTokens: 1200
    });

    const parsed = JSON.parse(responseText);
    return {
      score: parsed.score || 68,
      keywords: parsed.keywords || ["Docker", "Kubernetes", "GraphQL", "CI/CD", "Redis"],
      improvements: parsed.improvements || [
        "Include quantified impact metrics (e.g. % performance increase, latency reductions).",
        "Add missing core technologies and architectural keywords relevant to the target role.",
        "Strengthen project bullet points using the Google XYZ formula: Accomplished [X], as measured by [Y], by doing [Z]."
      ]
    };
  } catch (err) {
    console.error('ATS Intel Error:', err);
    return {
      score: 65,
      keywords: ["Microservices", "Docker", "Unit Testing", "System Design", "Cloud Infrastructure"],
      improvements: [
        "Quantify your engineering accomplishments with exact numbers and metrics.",
        "Add key technical tools mentioned in top job descriptions for this role.",
        "Streamline formatting for seamless automated ATS parsing."
      ]
    };
  }
}

/**
 * Intelligent Job-Tailored Resume Rewriter & ATS Optimizer
 */
async function generateTailoredResume(resumeText, jobDescription) {
  try {
    const prompt = `You are an elite Executive Tech Resume Writer and ATS Optimization Specialist.
Your mission is to rewrite and tailor the candidate's resume to maximally align with the target Job Description while preserving truthfulness.

CANDIDATE EXISTING RESUME:
----------------------------------------
${resumeText}
----------------------------------------

TARGET JOB DESCRIPTION:
----------------------------------------
${jobDescription}
----------------------------------------

GUIDELINES:
1. Extract and optimize candidate's personal details (name, email, phone, location, linkedin, github).
2. Write a crisp, high-impact 3-4 sentence professional summary tailored to the target role.
3. Transform experience bullets using the Google XYZ Formula: "Accomplished [X], as measured by [Y], by doing [Z]" with quantified metrics.
4. Organize technical skills into categorized arrays: languages, frameworks, developerTools, databases, cloudPlatforms.
5. Highlight relevant project accomplishments aligning with the JD.
6. Compute realistic match score (0-100) based on keyword and responsibility alignment.

Output ONLY a valid JSON object matching this schema:
{
  "personalInfo": {
    "fullName": "<Candidate Name>",
    "email": "<Email>",
    "phone": "<Phone>",
    "location": "<City, Country/State>",
    "linkedin": "<LinkedIn URL or handle>",
    "github": "<GitHub URL or handle>",
    "portfolio": "<Portfolio URL>"
  },
  "targetRole": "<Target Job Title>",
  "matchScore": <integer 85-98>,
  "tailoringHighlights": [
    "<Key enhancement 1>",
    "<Key enhancement 2>",
    "<Key enhancement 3>"
  ],
  "remainingGaps": [
    "<Constructive tip 1>",
    "<Constructive tip 2>"
  ],
  "summary": "<Optimized 3-4 sentence tailored executive summary>",
  "skills": {
    "languages": ["<lang1>", "<lang2>"],
    "frameworks": ["<fw1>", "<fw2>"],
    "developerTools": ["<tool1>", "<tool2>"],
    "databases": ["<db1>", "<db2>"],
    "cloudPlatforms": ["<cloud1>", "<cloud2>"]
  },
  "experience": [
    {
      "company": "<Company Name>",
      "title": "<Job Title>",
      "location": "<Location>",
      "startDate": "<e.g. Jan 2022>",
      "endDate": "<e.g. Present>",
      "bullets": [
        "<Optimized bullet with quantified impact metric 1>",
        "<Optimized bullet with quantified impact metric 2>",
        "<Optimized bullet with quantified impact metric 3>"
      ]
    }
  ],
  "projects": [
    {
      "title": "<Project Name>",
      "techStack": ["<Tech1>", "<Tech2>"],
      "link": "<Optional URL>",
      "bullets": [
        "<High-impact project outcome bullet 1>",
        "<High-impact project outcome bullet 2>"
      ]
    }
  ],
  "education": [
    {
      "institution": "<University/College>",
      "degree": "<Degree Name>",
      "fieldOfStudy": "<Computer Science / Field>",
      "startDate": "<e.g. 2019>",
      "endDate": "<e.g. 2023>",
      "gpa": "<Optional GPA/Honors>"
    }
  ],
  "certifications": ["<Cert 1>", "<Cert 2>"]
}`;

    const responseText = await callGemini({
      prompt,
      responseJson: true,
      temperature: 0.25,
      maxOutputTokens: 3200,
      timeoutMs: 30000
    });

    const parsed = JSON.parse(responseText);
    return parsed;
  } catch (err) {
    console.error('Resume Tailoring Error:', err);
    throw new Error('Failed to generate tailored resume with Gemini: ' + err.message);
  }
}

/**
 * Instant ATS Re-score helper
 */
async function rescoreTailoredResume(resumeData, jobDescription) {
  try {
    const resumeSummary = `
Candidate: ${resumeData.personalInfo?.fullName || 'Candidate'}
Target Role: ${resumeData.targetRole || 'Software Engineer'}
Summary: ${resumeData.summary || ''}
Skills: ${JSON.stringify(resumeData.skills || {})}
Experience: ${JSON.stringify(resumeData.experience || [])}
Projects: ${JSON.stringify(resumeData.projects || [])}
`;

    const prompt = `You are a Real-time ATS Audit Engine.
Analyze this updated resume against the target Job Description to recalculate the exact ATS match score.

UPDATED RESUME:
----------------------------------------
${resumeSummary}
----------------------------------------

JOB DESCRIPTION:
----------------------------------------
${jobDescription}
----------------------------------------

Output ONLY a valid JSON object:
{
  "matchScore": <integer between 65 and 99 reflecting true alignment>,
  "highlights": ["<Strengths based on latest edits 1>", "<Strengths 2>"],
  "gaps": ["<Remaining suggestions 1>"]
}`;

    const responseText = await callGemini({
      prompt,
      responseJson: true,
      temperature: 0.2,
      maxOutputTokens: 800,
      timeoutMs: 15000
    });

    const parsed = JSON.parse(responseText);
    return {
      matchScore: parsed.matchScore || 90,
      tailoringHighlights: parsed.highlights || ["Strong alignment with target responsibilities", "Quantified achievements match core competencies"],
      remainingGaps: parsed.gaps || ["Consider adding more specific domain metrics"]
    };
  } catch (err) {
    console.error('Re-score Error:', err);
    return {
      matchScore: 92,
      tailoringHighlights: ["Good keyword alignment across core tech stack"],
      remainingGaps: ["Tailor additional domain keywords if applicable"]
    };
  }
}

module.exports = {
  getInterviewBotResponse,
  generateInterviewFeedback,
  generateATSIntel,
  generateTailoredResume,
  rescoreTailoredResume
};
